language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.1 WP_MULTISITE=0
  - WP_VERSION=4.1 WP_MULTISITE=1
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=1
  - WP_VERSION=3.9 WP_MULTISITE=0
  - WP_VERSION=3.9 WP_MULTISITE=1
  global:
  - PHPCS_DIR=/tmp/phpcs
  - secure: SMPml9xPNS2AGYZyRzGU83qdH85tBI4VB4mTtRISE1DB64Tjg9WcD1Zrztw2BlynARgHNZD/BzVDVhQvIjzhRWvqPGTGw22RgikaZJV+eCBMaZ4VIP9uSdsgCWRpFkPdJbnVARfS9eWEehaacVOVM0CKRN8G3GQYWLVE5+m1LIw=
sudo: false
install:
- git config --global user.email "paul@hmn.md"
- git config --global user.name "Paul de Wouters"
notifications:
  email: false
  slack:
    secure: ZyXhKGpR/VtggG3vcCaZ+50HBn4STi2fOvMKrmZaeS44s+j6lhkYt7qT1UeU1o2Vox2WCrdqfZqT370f4OV3izAgf7Ln+vIYxZvCywL2Cyt4YbHVPX0pMwuDuAW6a1zG5oP87CFZh9YYCHQ6HfX9ATKtnqiuMFx/SjOcD1Yb4Lk=
before_script:
- composer selfupdate --quiet
- composer install -n --prefer-dist --no-progress
- bash bin/prepare.sh
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then $PHPCS_DIR/scripts/phpcs --standard=WordPress-Extra --ignore=$PHPCS_IGNORE; fi
- phpunit --testsuite backup --coverage-clover=coverage.clover
- phpunit --testsuite schedule --coverage-clover=coverage.clover
- phpunit --testsuite other --coverage-clover=coverage.clover
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
