# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
  - 5.3
  - 5.4
  - 5.5

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

sudo: false

notifications:
  hipchat:
      secure: "KSkj1N4CVYf8/ZWhoogK/dTh7pxvqNN3E0VM/VBGnBJVAOWvXCB5RB/nUBYcdG5rNgjvzcIAUr23MIsyzowbYw2uBEmpZeIxkmryKXsby8VyDrHQZppawLRjOpfBk9PsrH4e8/BlNc0acBvGHVBU0giL0lj3WlXNKOKNBdrf2PE="
      email: false

# Clones WordPress and configures our testing environment.
before_script:
    - mkdir -p build/logs
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
